[workspace]
authors = ["Thogar77 <kruczek@student.agh.edu.pl>"]
channels = ["conda-forge"]
name = "Projekt"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build-conan = "CMAKE_POLICY_VERSION_MINIMUM=3.5 conan install conanfile.py --build missing --output-folder install/conan --deployer=full_deploy --deployer-folder install/conan/deploy"

[tasks.build-all]
cmd = "bash -c 'source install/conan/conanbuild.sh && cmake --preset conan-release && cmake --build install/conan/build/Release'"

[dependencies]
conan = ">=2.26.1,<3"
